/*
Gregory Macri

This program reads in 3 text files: 2 files containing random float values 
and 1 file containing operation symbols. Random numbers are generated to 
simulate the time needed to get each value and the value of the two numbers
are calculated using the given sign along with the longest time of the two
values to be generated. 
*/

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <math.h>
#include <unistd.h>

float inputValue[2];//global variable for input values from input threads
int inputTime[2];//global variable for random times generated by threads

int ready[2];//used for conditionals to communicate between threads
int stop[2];//used to notify other threads if thread has ended

/*thread function used to get input values from T1 and T2 files and generate
random time values*/
void *input(void *threadID)
{
   int time, retval;//holds random time generated, return value from fscanf 
   float value;//holds value read from file
   
   int id = (long)threadID;//cast and store threadID in id
   unsigned int seed = id;//get seed for rand_r

   FILE *source;//file pointers for reading and writing
   FILE *out;

   //opens different files for reading and writing based on id
   if(id == 0)
   {
     if(access("T1.txt", F_OK) == -1)//check if file exists
     {
       printf("ERROR: T1.txt DOES NOT EXIST\n");
       stop[0] = 0;
       exit(1);
     }
     source = fopen("T1.txt","r");
     out = fopen("T1.out","w");
   }
   else
   {
     if(access("T2.txt", F_OK) == -1)
     {
       printf("ERROR: T2.txt DOES NOT EXIST\n");
       stop[1] = 0;
       exit(1);
     }
     source = fopen("T2.txt","r");
     out = fopen("T2.out","w");
   }

   retval = fscanf(source,"%f",&value);//read first float from file

   while(retval == 1)//while numbers are left in file
   {
      time = rand_r(&seed);//generate random number

      //generate time based on id and write to file
      if(id == 0)
      {
	inputTime[0] = (time % 4) + 1;
	fprintf(out,"%d ",inputTime[0]);
      }
      else
      {
	inputTime[1] = (time % 4) + 2;
	fprintf(out,"%d ",inputTime[1]);
      }

      inputValue[id] = value;//store value read into global variable

      ready[id] = 0;//set ready based on id to 0

      while(ready[id] == 0)//wait until ready is no longer zero
      {
	if(stop[0] == 0 || stop[1] == 0)//if while waiting either stop 0,break
	  break;
      }

      if(stop[0] == 0 || stop[1] == 0)//if stop set for any thread leave loop
	break;
      
      retval = fscanf(source,"%f",&value);//get next char from file
   } 

   ready[id] = 0;//set ready and stop to zero
   stop[id] = 0;

   fclose(out);//close files
   fclose(source);

   pthread_exit(NULL);//exit thread
}

//thread function to read from T3 file and output to screen based on values
void *output(void)
{
  FILE *source = fopen("T3.txt","r");//open and read from T3
  char sign;//holds sign read from file
  float value;//holds value calculated using inputValues and signs

  while(stop[0] == -1 && stop[1] == -1)//while neither input thread has exited
  {
    while(ready[0] == -1 || ready[1] == -1)//wait for both input threads
    {
      if(stop[0] == 0 || stop[1] == 0)//if either input thread exits, break
	break;
    }

    if(stop[0] == 0 || stop[1] == 0)//if either input thread exits, break 
      break;

    fscanf(source,"%c",&sign);//read character from T3 and store in sign

    //based on sign, do calculation
    if(sign == '+')
      value = inputValue[0] + inputValue[1]; 
    else if(sign == '-')
      value = inputValue[0] - inputValue[1];
    else if(sign == '*')
      value = inputValue[0] * inputValue[1];
    else
      value = inputValue[0] / inputValue[1];

    //determine which time is greater and print
    if(inputTime[0] > inputTime[1])
      printf("%.1f(%d) ",value,inputTime[0]);
    else
      printf("%.1f(%d) ",value,inputTime[1]);
    
    ready[0] = -1;//let input threads read in another value
    ready[1] = -1;
  }

  printf("\n");//print newline after loop exit
  pthread_exit(NULL);//exit thread
}

int main(int argc, char *argv[])
{
  pthread_t threads[3];//used to store threads

  stop[0] = -1;//set stop and ready values to -1
  stop[1] = -1;
  ready[0] = -1;
  ready[1] = -1;

  //create input and output threads
  pthread_create(&threads[0], NULL, input,(void*)0);
  pthread_create(&threads[1], NULL, input,(void*)1);
  pthread_create(&threads[2], NULL, output,0);

  //wait for all threads to exit
  pthread_join(threads[0], NULL);
  pthread_join(threads[1], NULL);
  pthread_join(threads[2], NULL);

  exit(0);//exit main thread
}
